name: banco_digital
publish_to: none
environment:
  sdk: ^3.9.0

workspace:
  - packages/core/core_errors
  - packages/features/feature_accounts
  - packages/app
  - packages/core/core_network
  - packages/features/feature_onboarding
dev_dependencies:
  melos: ^8.9.0

melos:
  command:
    version:
      branch: main
  scripts:
    analyze:
      run: melos exec -- flutter analyze
      description: Analiza todos los paquetes
    test:
      run: melos exec --dir-exists=test -- flutter test
      description: Corre tests donde haya carpeta test