name: banco_digital
publish_to: none
environment:
  sdk: ^3.9.0

workspace:
  - packages/core/core_errors
  - packages/features/feature_accounts
  - packages/app
  - packages/core/core_network
  - packages/features/feature_onboarding
  - packages/core/core_ui
  - packages/core/core_storage
  - packages/core/core_telemetry
  - packages/features/feature_exchange
  - packages/features/feature_notifications
  - packages/features/feature_personalization
dev_dependencies:
  melos: ^8.9.0

melos:
  command:
    version:
      branch: main
  scripts:
    analyze:
      run: melos exec -- flutter analyze
      description: Analiza todos los paquetes
    test:
      run: melos exec --dir-exists=test -- flutter test --exclude-tags integration
      description: Corre tests donde haya carpeta test (sin los de integración)
    test:changed:
      run: melos exec --diff=HEAD --include-dependents --dir-exists=test -- flutter test --reporter expanded --exclude-tags integration
      description: Corre tests solo de lo modificado sin commitear + dependientes     