name: core_telemetry
resolution: workspace
description: "Telemetría con privacidad garantizada: Crashlytics, Analytics y Performance."
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.13.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core_errors: ^0.0.1
  firebase_core: ^4.14.0
  firebase_crashlytics: ^5.4.0
  firebase_analytics: ^12.6.0
  firebase_performance: ^0.11.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
